name: Run IR AI Summarizer

on:
  schedule:
    # Runs every day at 8am UTC 
    - cron: "0 8 * * *"
  workflow_dispatch:   # allows manual runs from GitHub UI

jobs:
  run-summarizer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug secrets   # Debug for the secret
        run: |
          echo "EMAIL_ADDRESS set? -> ${{ secrets.EMAIL_ADDRESS != '' }}"
          echo "EMAIL_PASSWORD set? -> ${{ secrets.EMAIL_PASSWORD != '' }}"

      - name: Run summarizer
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python scrape_and_summarize.py
